apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    k8s-app: pod-mariadb-monitor 
  name: pod-mariadb-monitor
spec:
  selector:
    matchLabels:
      deployment: mariadb
  podMetricsEndpoints:
  - port: mariadb-metrics
    interval: 30s
    scheme: http
