apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prom-app
  name: prom-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-app
  template:
    metadata:
      labels:
        app: prom-app
    spec:
      containers:
      - name: prom-app
        image: quay.io/jvarela01/prometheus-example-app:latest
        ports:
        - name: web
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prom-app
  name: prom-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: web
  selector:
    app: prom-app
  type: ClusterIP
